// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Covid struct {
	Dailyconfirmed *string `json:"dailyconfirmed"`
	Dailydeceased  *string `json:"dailydeceased"`
	Dailyrecovered *string `json:"dailyrecovered"`
	Date           *string `json:"date"`
	Dateymd        *string `json:"dateymd"`
	Totalconfirmed *string `json:"totalconfirmed"`
	Totaldeceased  *string `json:"totaldeceased"`
	Totalrecovered *string `json:"totalrecovered"`
}

func (Covid) IsEntity() {}
