// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Route struct {
	DisplayName *string `json:"display_name"`
	ID          *string `json:"id"`
}

func (Route) IsEntity() {}
