// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Metro struct {
	ID          string `json:"id"`
	DisplayName string `json:"display_name"`
}

func (Metro) IsEntity() {}

type AddMetro struct {
	ID          string `json:"id"`
	DisplayName string `json:"display_name"`
}
